### PR TITLE
Removed hardcoded parameters. Defaults loaded at runtime.

### PR DESCRIPTION
**Pull request by IamDH4**
I've removed hardcoded parameters for ffmpeg on the output side. They are now specified in the config file. Defaults are loaded at run-time if the file does not already have the parameters set.

First step in solving #7

### CODE REVIEW

**Comment by rikai** [comment]
I am going to recommend holding off on merging this until scaling of the bar visualization to the new parameters automatically is figured out :)

**Comment by IamDH4** [comment]
Scaling has been implemented and ready for testing. Interested to see how well this works with HiDPI. I cannot test that.

**Comment by IamDH4** [comment]
Scaling seems to be working well now. Tested at 480p, 720p, and 1080p. Currently resolutions must be set from the config file, and loaded at launch. Will implement selection capability in a later commit.

**Comment by IamDH4** [comment]
This is already baked into the `feature-newgui` branch. Closing this request.

**Pull request closed without merging**
